### ISSUE TITLE
Updating tau1/tau2 will have no effect

### ISSUE THREAD

**Issue by vineetbansal** [ComputationalCryoEM/aspyre#1]
Perhaps I'm missing something - but updating tau1/tau2 as it's done here would have no effect since we're only updating the local variables which are not used in `run_svm` at all, and just die after the method returns:

https://github.com/computationalcryoem/aspyre/blob/56481584096f733ca2e441d1593c9ceca2f7dcdc/src/aspyre/apple/apple.py#L198

Did we intend to update `self.tau1` and `self.tau2` instead?

**Comment by troycomi** [comment]
I think it should be picker.tau which is modified (picker.tau += 500).  That should eliminate lines 188-190 as well.

My own two cents, that check would be better served in the run_svm function itself.  Another useful parameter would be a maximum number of iterations or another test to eliminate the possibility of infinite loops.  Not sure of runtime or the sizes of segmentation, but np.zeros/ones uses memory for allocation.  Perhaps a better test there is to sum segmentation and check if it equals 0 or segmenation.size.

**Comment by junchaoxia** [comment]
I think @troycomi might be right. As fas as I understand, the process to each micrograph is independent and have different picker which need to optimize the parameters.

**Comment by junchaoxia** [comment]
@troycomi @vineetbansal  Just got confirmed from Ayelet, it should be the tau1 and tau2 in the picker object to be adjusted when there is no particle picked for default values which is a very rare situation.
